#! /bin/bash
# vi:set nu ai ap aw smd showmatch tabstop=4 shiftwidth=4 expandtab:

function NOT_ROOT_USER {
    echo ""
    echo "##### !!!!! YOU MUST BE ROOT TO RUN THIS !!!!! #####"
    echo "##### PLEASE USE sudo    #####"
    echo ""
    exit 1
}

function DIE {
    echo ""
    echo "##### Failure: $*"
    echo ""
    read -p "Press enter to continue or ^C to abort ---> "
    return 0
}

function Install {
    echo "############### installing apt-package $1"
    apt-get install -y ${1?Must declare package} || DIE "install $1 failed"
    echo ""
}

## list of pip packages to install
export piplist=( config jinja2 pymongo pyyaml xlrd tabulate pandas pexpect paramiko lxml sqlalchemy plotly scipy matplotlib pyang python-dateutil pytz pkgutil-resolve-name jira grpcio-tools mysql-connector-python grpcio )


# ensure we are root
[[ "$EUID" -eq 0 ]] || NOT_ROOT_USER

echo ""
echo "################################################################"
echo "#                                                              #"
echo "#    start of $(basename $0)                                   #"
echo "#                                                              #"
echo "################################################################"
echo ""

## start of the apt package installs
apt-get update

Install software-properties-common

add-apt-repository -y ppa:deadsnakes/ppa || DIE "failure adding repo ppa:deadsnakes/ppa"

Install python3.7

Install python3-pip

Install python3-venv

Install python3.7-venv

## start of the python3.7 pip installs
export PIP_ROOT_USER_ACTION=ignore
#python3.7 -m pip install config jinja2 pymongo pyyaml xlrd tabulate pandas pexpect paramiko lxml sqlalchemy plotly scipy matplotlib pyang python-dateutil pytz pkgutil-resolve-name jira grpcio-tools mysql-connector-python grpcio
python3.7 -m pip install ${piplist[*]}

echo ""
echo "################################################################"
echo "#                                                              #"
echo "#    end of $(basename $0)                                     #"
echo "#                                                              #"
echo "################################################################"
echo ""
exit 0
